// <auto-generated />
namespace MMSLHMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tblLoandistribution_LoanStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tblLoandistribution_LoanStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "202108090533235_tblLoandistribution_LoanStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
