// <auto-generated />
namespace MMSLHMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tblLoanDistribution_Interest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tblLoanDistribution_Interest));
        
        string IMigrationMetadata.Id
        {
            get { return "202108051030551_tblLoanDistribution_Interest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
