// <auto-generated />
namespace MMSLHMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MMSLHMS_DMS_LastAll : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MMSLHMS_DMS_LastAll));
        
        string IMigrationMetadata.Id
        {
            get { return "202101050603318_MMSLHMS_DMS_LastAll"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
